### ISSUE TITLE
Erro "Modo Trial"

### ISSUE THREAD

**Issue by marlonassuncao** [vindi/vindi-woocommerce-subscriptions#105]
Após atualizar para nova versão 5.3 o plugin aparece um aviso de Modo de Testes sem estar ativo

<img width="1167" alt="screen shot 2018-10-05 at 14 41 38" src="https://user-images.githubusercontent.com/1735680/46551199-80c39980-c8ad-11e8-87a1-e9ff28da3568.png">

**Comment by laerte-guimaraes** [comment]
@marlonassuncao verificamos que o Wordpress mantém o status trial em cache, e por isso não atualiza para o status na plataforma da Vindi.

Fizemos um ajuste na versão 5.3.1 que corrige esse comportamento.

Se você estiver em alguma versão anterior, basta atualizar o plugin, e se você já estiver na versão 5.3.1, você deve desativar/excluir e instalar o plugin novamente.

Pode realizar os procedimentos e nos informar do comportamento?

Abraços !

**Comment by marlonassuncao** [comment]
Boa tarde. Removi a versão e instalei a nova versão, porém continua o problema:

<img width="1214" alt="screen shot 2018-10-08 at 16 03 27" src="https://user-images.githubusercontent.com/1735680/46628513-2ed07d00-cb14-11e8-90cf-896de582197d.png">

Desativei, ativei e se manteve o erro. Fiz downgrade a Versão 4.0.2 e o problema foi sanado.

Abraços!

**Comment by laerte-guimaraes** [comment]
@marlonassuncao acabamos de lançar a versão 5.3.2, pode verificar o comportamento? :smile:

**Comment by laerte-guimaraes** [comment]
@marlonassuncao validamos o comportamento correto na última versão!

Estarei fechando essa Issue. Porém, qualquer dúvida, sinta-se à vontade para reabri-la :smile:
