### ISSUE TITLE
O plugin ainda está sendo ativamente desenvolvido?

### ISSUE THREAD

**Issue by guicz** [vindi/vindi-woocommerce-subscriptions#161]
Gostaria de saber se este plugin continua em desenvolvimento ativo pois as últimas atualizações aqui foram feitas ainda em 2020.

Obrigado

**Comment by ThalitaNsc** [comment]
Boa tarde, tudo bem? Sim, ainda trabalhamos nele, mas não realizamos ainda atualizações voltadas a melhorias.

**Comment by thalita-nascimento-vindi** [comment]
Boa Tarde, o plugin ainda está disponível para download, mas não realizamos mais atualizações nem correções nele. 
Temos uma versão 2 do nosso plugin que é onde trabalhamos em melhorias e correções.
https://github.com/vindi/vindi-woocommerce
