### ISSUE TITLE
Cancelamento da uma subscription cancela a membership também

### ISSUE THREAD

**Issue by renanno** [vindi/vindi-woocommerce-subscriptions#22]
Boa noite

Estou testando o Vindi com Woocommerce + WC Subscriptions + WC Memberships. A combinação parece perfeita, mas estou tendo alguns problemas.

Criei dois planos mensais, com valores diferentes e features diferentes. Notei que quando o Vindi está ativo, some as opções de tempo na criação de um produto do tipo subscription (a cada X meses por X vezes ou tempo indeterminado).

Se um usuário contrata essa subscription com ciclo de 1 mês e, dentro desse período, cancela a assinatura, o sistema cancela a subscription (status cancelled) e já cancela também a membership vinculada.

Exemplo: eu contrato um plano em 01/10/16; o segundo ciclo deveria ocorrer em 01/11/16. Mas eu cancelo a assinatura em 15/10/16. O correto é a assinatura e a membership durarem até 01/11/16 e não processar novos pagamentos. Afinal o usuário pagou aquele mês cheio.

O que ocorre hoje é que no dia 15, quando eu cancelei a subscription, ele cancela também a membership.

É alguma configuração errada que eu fiz, ou o plugin da Vindi que tem esse "bug"?

Obrigado!
Renan

**Comment by renanno** [comment]
Essa habilidade parece não estar acontecendo: https://docs.woocommerce.com/document/woocommerce-memberships-subscriptions-integration/#section-6

"When the subscription is cancelled (**and goes into the “pending cancellation” status**), its associated membership will also be pending cancellation as a result.

**Membership access will continue until the end of the pending cancel period** — once the subscription is fully cancelled, the membership will be as well, removing membership access to any restricted content or discounts."

Obrigado!

**Comment by lyoncesar** [comment]
Boa tarde @renanno.
Estamos ajustando o plugin para que o cancelamento do Memberships tenha o funcionamento adequado. A previsão de entrega é até o dia 23/10, próxima segunda-feira.
Qualquer dúvida nos avise.

Abs.
