### ISSUE TITLE
Perdendo parâmetros ao salvar o produto.

### ISSUE THREAD

**Issue by jarbasdossantos** [vindi/vindi-woocommerce-subscriptions#5]
Quando edito o produto, e não altero o campo "**Plano da Vindi**", está perdendo os seguintes parâmetros na tabela "**wp_postmeta**": "**_subscription_period**" e "**_subscription_period_interval**".
Diante disso, preciso selecionar outro plano no campo **Plano da Vindi**, salvar, selecionar novamente o plano correto e salvar, para aí sim ele conseguir salvar os valores dos campos descritos.

**Comment by jarbasdossantos** [comment]
Resolvi! Analisando o código, vi que o tem o seguinte campo:
`<input type="hidden" name="_subscription_length" value=""></input>`

Vi que esse campo é alimentado através do **change** do campo **Plano da Vindi**.
Sendo assim, quando não modifico esse campo, o hidden field fica sem valor. Editei o arquivo `/plugins/vindi-woocommerce-subscriptions/assets/js/simple-subscription-fields.js`, adicionando o `.change()`.

`(
  function ($) {
    'use strict';
    $(function() {
      var plan_infos = $("#vindi_subscription_plan").data('plan-info');

```
  $("._subscription_period_interval_field, ._subscription_period_field, ._subscription_length_field").remove();

  $("#vindi_subscription_plan").change(function(){
    var id   = $(this).val();
    var plan = plan_infos[id];

    console.log(plan);

    $("input[name=_subscription_period_interval]").val(plan.interval_count);
    $("input[name=_subscription_period]").val(plan.interval.toString().replace(/s/g, ''));
    $("input[name=_subscription_length]").val(plan.billing_cycles);
}).change();
});
```

  }(jQuery)
);
`

Se poderem realizar essa alteração, eu agradeço!

**Comment by asagalo** [comment]
Eu vi que não fazia muito sentido os campos hidden, já que existem os próprios campos do WCS que possuem o mesmo nome, que por padrão já estão preenchidos, creio que o problema não ocorrerá mais. Obrigado pela sua contribuição @blasterweb :D
