### ISSUE TITLE
Imagem cartão de crédito no carrinho sem classe css

### ISSUE THREAD

**Issue by Frisoni** [vindi/vindi-woocommerce-subscriptions#54]
Quando o usuário já tem um cartão cadastrado, no momento do checkout aparece a imagem do Cartão de Crédito.
Com o tema que estou utilizando essa imagem fica desconfigurada, conforme print abaixo.
![cartao-credito](https://user-images.githubusercontent.com/12817135/33435442-53859c0c-d5c9-11e7-88f2-b8ed3ec0b6f5.png)
A imagem é incluida através de uma div no arquivo templates/creditcard-checkout.html.php linha 22.
Mas como não há nenhuma classe atribuída a ela eu não consigo manipular através do CSS.
Apenas incluir uma classe na div já resolve o problema.

**Comment by laerte-guimaraes** [comment]
Corrigido no Pull #63
