### ISSUE TITLE
Atualizar valor da assinatura no Woo ao término do cupom

### ISSUE THREAD

**Issue by Frisoni** [vindi/vindi-woocommerce-subscriptions#57]
Quando utilizamos cupons de descontos com ciclos, por exemplo 3 meses, ao término do desconto a assinatura na vindi tem o valor alterado para o valor "cheio".
Porém, o mesmo não ocorre no Woo causando uma diferença entre o valor do pedido no Woo e da fatura na Vindi.
Ao faturar o ultimo pedido com desconto já poderia alterar o valor da assinatura no Woo para deixar correto para o próximo ciclo.

**Comment by renanno** [comment]
Upvote pra esse pedido.

**Comment by Frisoni** [comment]
Alguma previsão para essa modificação?
Tá bem complicado de utilizar cupons com as assinaturas. Configuramos o cupom de um jeito no woo e tem que ficar conferindo como ficou na vindi depois da assinatura e ajustando.

**Comment by laerte-guimaraes** [comment]
@Frisoni e @renanno Tudo bem? :smile: 

Gostamos de sua sugestão porque nos auxilia na melhoria do Plugin, e já inserimos em nossa fila de Backlog (à fazer).

**Comment by laerte-guimaraes** [comment]
@Frisoni 
Quanto a previsão de entrega; Estamos atuando em algumas tarefas para melhoria do Plugin como Adição de Taxas, Sincronização de Status da Assinatura, Envio dos valores atuais do carrinho, entre outras que já  foram priorizadas.
Nas próximas atualizações estaremos atuando na sua sugestão.

Abraços!

**Comment by renanno** [comment]
Pessoal, eu vi que isso foi tagueado como **melhoria**. Isso não é uma melhoria, é **correção de um bug**.

Imaginem que eu ofereço ao meu cliente 30% de desconto na primeira mensalidade. Ao invés de pagar R$10 ele paga R$7 na primeira, o que está correto.

Aí na segunda mensalidade a Vindi cobra R$10 no cartão dele, mas no nosso site (onde o plugin opera) ele está vendo R$7. Ou seja, printamos na tela o valor de R$7 e cobramos no cartão o valor de R$10.

**Isso é um bug, não é uma melhoria**.

Se eu to cobrando R$10 do meu cliente, não posso informar que estou cobrando R$7, tenho que informar que cobrei R$10. Isso inviabiliza complementa a possibilidade de oferecermos descontos em X mensalidades.

Não entendo como pode isso não ser uma prioridade... É tipo ter um bug que não permite a cobrança no cartão, mas não priorizar porque eu quero fazer primeiro a melhoria de adicionar taxas nas cobranças, sendo que nem cobrar eu consigo. Nunca vi priorizarem melhoria ao invés de um bug sério como esse.

Hoje, pra mim (e imagino que para o @Frisoni também), a feature de descontos da forma como está é completamente inútil. Não posso correr o risco de ser processado pelo meu cliente porque to informando um valor X e cobrando um valor maior...

**Comment by Frisoni** [comment]
Atualizei a versão do Woo Subscriptions e notei que agora ele permite difinir um prazo para o cupom de desconto no próprio Woo.
NÃO TESTEI, mas imagino que se eu setar 3 meses no Woo e 3 meses na Vindi acabe resolvendo esse problema.

Mas, de qualquer forma, acredito que agora fique bem mais fácil pra implementar isso no plugin da vindi: levar a quantidade de vezes que o cupom será utilizado de acordo com o que está configurado no próprio cupom. Assim temos essa flexibilidade de ter cupons com diferentes prazos de desconto recorrente.

**Comment by laerte-guimaraes** [comment]
@Frisoni 
Foi adicionado no PR #94 a opção de utilizar o campo **Limite de uso por cupom**
![image](https://user-images.githubusercontent.com/31661772/44556423-147f4300-a710-11e8-9f6a-83f3054cc997.png)

Pode dar uma olhada? :smile:

**Comment by Frisoni** [comment]
Oi @laerte-guimaraes .
Não entendi essa modificação.
O limite de uso por cupom é quantas vezes o cliente pode usar um cupom e não tem nenhuma relação com os ciclos do cupom que comentei acima.

**Comment by laerte-guimaraes** [comment]
@Frisoni 
Alterei o campo para **Limite de uso por cliente**.
O _Limite de uso por cupom_ é global, e qualquer cliente que utilize o mesmo, consome esse limite.
Já o _Limite de uso por cliente_ é válido para aquele cliente específico.
![image](https://user-images.githubusercontent.com/31661772/44597128-0c251780-a7a5-11e8-838e-33f066d11f4a.png)

**Ex:**
> Você pode criar um desconto com **limite de uso** em 2 por cliente, e disponibilizá-lo na _Black Friday_.
Cada cliente que utilizar irá receber o desconto de **2 ciclos**, e você pode utilizar a _data de expiração do cupom_ no WooCommerce, para definir _até quando_ o cupom poderá ser utilizado.

A data de expiração é um campo do tipo _data_, e pode causar um *impacto indesejado* em empresas que utilizam recorrências semanais/diárias/bimestrais/semestrais/anuais

Essa é a única forma de disponibilizar a flexibilidade de utilizar **descontos personalizados**, sem prejudicar empresas que utilizam recorrências _diferentes de mensa_.

**Comment by Frisoni** [comment]
@laerte-guimaraes 
Achei confuso. Tá repetindo uma configuração que já existe na ultima versão do Woo Subs.
Agora tem esses 2 tipos novos de cupons para produtos com recorrência.
![image](https://user-images.githubusercontent.com/12817135/44599724-a25d3b80-a7ad-11e8-8fbd-f79f487edb30.png)
Aí quando um desses dois tipos é selecionado aparece um novo campo para informar quantos ciclos esse cupom será válido.
![image](https://user-images.githubusercontent.com/12817135/44599808-dafd1500-a7ad-11e8-8745-c828c35c1139.png)

Pelo que entendi do que você fez, se eu setar o limite de uso por cliente para 1, querendo que o desconto seja utilizado apenas no primeiro ciclo, se o cliente tentar fazer uma segunda assinatura usando o mesmo cupom ele não irá conseguir mais, por já atingiu o limite.

**Comment by laerte-guimaraes** [comment]
@Frisoni 
Realizei os ajustes, porém vale ressaltar que só irá funcionar com a versão 2.3 ou superior do **WooCommerce Subscriptions** :smile:

**Comment by Frisoni** [comment]
Boa!
