### ISSUE TITLE
Problema ao salvar o parâmetro "_subscription_period_interval"

### ISSUE THREAD

**Issue by jarbasdossantos** [vindi/vindi-woocommerce-subscriptions#6]
Quando seleciono um plano Anual não está sendo salvo o valor **12** na tabela `wp_postmeta`. Somente quando seleciono um plano mensal esse meta é atualizado, ficando com o valor de **1**.

**Comment by asagalo** [comment]
Oi @blasterweb, tudo bom? Cara, fizemos uma atualização que corrige o problema citado. Obrigado pela sua colaboração! Qualquer problema estou à disposição!
