### ISSUE TITLE
Validação quando o valor da compra é menor que o mínimo da parcela

### ISSUE THREAD

**Issue by rafawhs** [vindi/vindi-woocommerce-subscriptions#66]
Quando o **valor total** da comprar é _menor_ que o **valor mínimo da parcela** o plugin não exibe o select de parcelas, mas a validação acusa o erro: **Quantidade de Parcelas requerido.**

No caso, o cliente deseja pagar o valor integral em 1x no cartão mas não pode concluir a compra por causa do erro.

**Comment by rafawhs** [comment]
Alguma atualização?

**Comment by laerte-guimaraes** [comment]
Opa Rafael,

Foi realizado no PR #59 Porém a versão no Wordpress.org estará disponível até amanhã!

Atenciosamente.
