### ISSUE TITLE
Erro ao atualizar endereço sem o WooCommerce Subscriptions

### ISSUE THREAD

**Issue by rafawhs** [vindi/vindi-woocommerce-subscriptions#67]
O erro ocorre quando o usuário tenta atualizar seus endereços e o WCS está desativado:

> PHP Fatal error:  Uncaught Error: Call to undefined function wcs_user_has_subscription() in /(...)/wp-content/plugins/vindi-woocommerce-subscriptions/vindi-woocommerce-subscriptions.php:156

**Comment by deblynprado** [comment]
Mesmo problema aqui, me parece um problema com a função _wcs_user_has_subscription()_

**Comment by deblynprado** [comment]
# Problema

o Vindi tenta ver se o usuário tem uma subscription ativa no WCS mesmo se o WCS estiver desativado.

# Solução
Adicionada verificação se o WCS é um plugin ativo ou não antes de tentar usar as funções dele

**Comment by laerte-guimaraes** [comment]
@rafawhs Tudo bem? :smile: 

Realizamos a remoção dessa verificação no PR #83 e iremos disponibilizar na versão 5.0.0 assim que finalizarmos os testes necessários ok? :+1: 

Abraços!
