### ISSUE TITLE
Confirmação de pagamento com Status Aguardando não atualiza assinatura

### ISSUE THREAD

**Issue by Frisoni** [vindi/vindi-woocommerce-subscriptions#69]
Estou utilizando a opção de manter o pedido do cliente com o status de aguardando no plugin da Vindi.
Funciona ok para o pedido, porém a assinatura fica como aguardando também, quando deveria voltar a ficar ativa.

**Comment by Frisoni** [comment]
Talvez não seja bem o caso de um bug, mas mais para uma opção.
Explicando melhor, mantemos os pedidos com o status aguardando (seria um aguardando envio) até que o produto seja enviado, e aí passamos o pedido para concluido.
Porém, a assinatura fica com o status aguardando também. Poderia ter a opção de informar qual status da assinatura deveria receber ao confirmar o pagamento também.

**Comment by laerte-guimaraes** [comment]
@Frisoni o status processando não seria válido nesses casos?

Sendo assim, após o envio você alteraria o status para concluído.

**Comment by Frisoni** [comment]
@laerte-guimaraes É uma possibilidade.
Preferimos o status aguardando pois como fica visível para o cliente é de melhor entendimento.
Por exemplo, enviamos os produtos todo dia 8 de cada mês. Aí se alguém assina no dia 02/07 o próximo envio será apenas no mes seguinte, dia 08/08. Aí deixar o status como processando fica meio confuso, por isso optamos pelo status aguardando.

**Comment by laerte-guimaraes** [comment]
@Frisoni infelizmente o status padrão para e-commerces que utilizam sistemas de envio no WooCommerce é o 'Processando', e apesar de disponibilizarmos a opção de utilizar um status personalizado como o 'Aguardando', e o mesmo ser mais intuitivo para o consumidor, o comportamento padrão dele no WooCommerce é considerar o pedido como aguardando pagamento, e não funciona como esperamos nesse caso (preparação do pedido).
Você pode também consultar o [artigo](https://www.yogh.com.br/blog/status-do-pedido-e-notificacoes-de-e-mail-do-woocommerce/).
