### ISSUE TITLE
Assinatura criada no Woo não existe na Vindi

### ISSUE THREAD

**Issue by Frisoni** [vindi/vindi-woocommerce-subscriptions#73]
Em alguns casos, quando no momento do registro da assinatura na Vindi apresenta um erro 422 na API, (falha no telefone, falha no método de pagamento, etc) acaba ficando a assinatura criada no Woo, dando a entender ao cliente que está tudo ok. Mas na vindi, não há nem sinal de assinatura, fatura ou qualquer outra coisa.
Nesses casos, o ideal seria nem deixar criar a assinatura no Woo, mas caso não seja possível, o retorno do erro 422 deveria pelo menos cancelar a assinatura que foi criada para manter os dois sistemas sincronizados.

**Comment by laerte-guimaraes** [comment]
Olá, Tudo bem?

Desculpe o transtorno;

Essa questão foi corrigida no Pull #71 pode verificar?

Qualquer dúvida, estamos a disposição ;)

**Comment by Frisoni** [comment]
Oi Laerte.
Eu já havia implementado manualmente essa correção do telefone. Tive algumas assinaturas depois disso com sucesso.
Mas ontem o problema foi  no método de pagamento, conforme log abaixo. E a assinatura foi criada no Woo mas não na Vindi.
422 Unprocessable Entity
{"errors":[{"id":"invalid_parameter","parameter":"card_number","message":"inválido(a)"}]}
04-15-2018 @ 20:46:10 - Falha ao registrar o método de pagamento. Verifique os dados e tente novamente.

**Comment by laerte-guimaraes** [comment]
@Frisoni 

O erro continua acontecendo?

A mensagem informada ocorre quando o número do cartão não é válido.

**Comment by Frisoni** [comment]
Confirmando que não tive mais este problema nos ultimos meses.
